# API Configuration
openai:
  api_key: "YOUR API KEY"
  model: "gpt-4-turbo"

ollama:
  base_url: "http://localhost:11434"
  model: "gemma3:4b"

# Database Configuration
database:
  path: "articles.db"